print("Welcome to the tip calculator!")
totalbill=float(input("What was the total bill? $" ))
tip=float(input("How much tip would you like to give? 10, 12, or 15?"))
no_of_people=int(input("How many people to split the bill with? "))
totalbill=totalbill+((tip/100)*totalbill)
ind_bill=round(totalbill/no_of_people,2)
print(f"Each person has to pay {ind_bill}")
